# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_EXPLOITANT:   ROLE_USER
        ROLE_ADMIN:        [ROLE_USER,ROLE_ADMIN]
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN,ROLE_SUPER_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
      main:
          pattern: ^/
          form_login:
              provider: fos_userbundle
              csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
          logout:       true
          anonymous:    true

          logout:
              path:  /logout
              target:  /
          anonymous:    true

    access_control:
        - { path: ^/register/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register/confirmed/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, role: ROLE_USER }


